# Generated by Django 2.2.3 on 2019-07-24 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_category_name', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ('employee_category_name',),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=256)),
                ('date_of_birth', models.DateField()),
                ('employee_age', models.IntegerField(default=None, max_length=4)),
                ('employee_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='management.EmployeeCategory')),
            ],
            options={
                'ordering': ('employee_name',),
            },
        ),
    ]
