# Generated by Django 2.2.3 on 2019-07-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_age',
            field=models.IntegerField(default=None),
        ),
    ]
