# Generated by Django 2.2.3 on 2019-07-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20190724_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_age',
            field=models.IntegerField(),
        ),
    ]
